---
#HOW TO RUN
#cd /home/ansible/devops-school/ansible
#ansible-playbook -i inventory.yml task1/grub-modify.yml --ask-become-pass

- name: Change default GRUB options and run grub2-mkconfig
  hosts: vm-nodes-centos
  remote_user: ansible
  become: yes
  become_method: sudo
  gather_facts: yes

  tasks:

#Two tasks below we need for case when variables are already defined one by one

  - name: Check if net.ifnames is not already defined
    lineinfile:
      state: absent
      path: /etc/default/grub
      regexp: 'net.ifnames='
    check_mode: true
    register: check_net_ifnames

  - name: Check if biosdevname is not already defined
    lineinfile:
      state: absent
      path: /etc/default/grub
      regexp: 'biosdevname='
    check_mode: true
    register: check_biosdevname 

  # This task find the proper string and append it with given items
  - name: "GRUB Options added 'inet.ifnames' and 'biosdevname' "
    lineinfile:
      path: /etc/default/grub
      regexp: '^GRUB_CMDLINE_LINUX="(.*?)"'
      line: 'GRUB_CMDLINE_LINUX="\1 net.ifnames=0 biosdevname=0"'
      state: present
      backrefs: yes
    notify: 
      - Fix-network-and-write-grub-changes
    when: 
      - check_net_ifnames.found == 0
      - check_biosdevname.found == 0

# Selective appends for ifnames only
  - name: "GRUB Options added 'inet.ifnames' "
    lineinfile:
      path: /etc/default/grub
      regexp: ^GRUB_CMDLINE_LINUX="(.*?)"
      line: 'GRUB_CMDLINE_LINUX="\1 net.ifnames=0"'
      state: present
      backrefs: yes
    notify: 
      - Fix-network-and-write-grub-changes
    when: 
      - check_net_ifnames.found == 0
      - check_biosdevname.found == 1

# Selective appends for biosdevname only

  - name: "GRUB Options added 'biosdevname' "
    lineinfile:
      path: /etc/default/grub
      regexp: ^GRUB_CMDLINE_LINUX="(.*?)"
      line: 'GRUB_CMDLINE_LINUX="\1 biosdevname=0"'
      state: present
      backrefs: yes
    notify: 
      - Fix-network-and-write-grub-changes
    when: 
      - check_net_ifnames.found == 1
      - check_biosdevname.found == 0
   
  handlers:
    - name: Copy Network interface config file
      copy:
        remote_src: yes
        src: /etc/sysconfig/network-scripts/ifcfg-enp0s5
        dest: /etc/sysconfig/network-scripts/ifcfg-eth0   
      listen: Fix-network-and-write-grub-changes  

    - name: Network configuration NetIfName Replaced
      replace:
        path: /etc/sysconfig/network-scripts/ifcfg-eth0
        regexp: '=enp0s5'
        replace: '=eth0'
      listen: Fix-network-and-write-grub-changes

    - name: Write-changes-GRUB to output file
      shell: grub2-mkconfig -o /boot/grub2/grub.cfg
      listen: Fix-network-and-write-grub-changes
    
    - name: Reboot machines to implement GRUB options and check
      reboot:
        msg: "Reboot initiated by Ansible"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 10
        post_reboot_delay: 30
        test_command: whoami
      listen: Fix-network-and-write-grub-changes