---
# handlers file for web-server-deploy
- name: Restart Apache2 service for Centos
  systemd:
    service: httpd
    state: restarted
  listen: restart-apache-service
  when: ansible_os_family == "RedHat"