#ansible-playbook -i inventory.yml task1.yml --ask-become-pass
---
- name: httpd package installed
  hosts: vm-nodes-centos
  remote_user: ansible
  become: yes
  become_method: sudo
  gather_facts: yes

  tasks:

  - name: HTTPD package is Installed
    dnf:
      name: httpd
      state: present
#    register: output

  - name: Make sure a service is running
    systemd:
      state: started
      name: httpd
      enabled: yes
    register: output

  - name: Firewall permissive TCP rule added via firewalld
    firewalld:
      service: http
      permanent: yes
      state: enabled
      zone: public
      permanent: yes
      immediate: yes
#    register: output
 
  - name: Index.html file loaded to /var/www/html/index.html
    copy:
      src: /home/ansible/devops-school/ansible/template-index.html
      dest: /var/www/html/index.html
    register: output

  - debug:
      msg: "{{ output }}"
